document.addEventListener("DOMContentLoaded",()=>{
const box=document.getElementById("details"),id=new URLSearchParams(location.search).get("id"),p=getProblems().find(x=>x.id===id);
if(!p){box.innerHTML='<div class="detail-card"><h1>Problem not found</h1><a class="text-link" href="problems.html">← Back to problems</a></div>';return}
let sols=JSON.parse(localStorage.getItem("ps_solutions_"+id)||"[]");
function render(){box.innerHTML=`<div class="detail-layout"><section class="detail-card"><a class="text-link" href="problems.html">← All problems</a><p style="margin-top:25px"><span class="status ${p.status==="SOLVED"?"solved":p.status==="IN PROGRESS"?"progress":"open"}">${esc(p.status)}</span></p><h1>${esc(p.title)}</h1><p>${esc(p.description)}</p><div class="problem-meta"><span>📁 ${esc(p.category)}</span><span>⚡ ${esc(p.urgency)}</span><span>📍 ${esc(p.location||"Not specified")}</span><span>🆔 ${esc(p.id)}</span></div><hr><h2>Solutions (${sols.length})</h2><div>${sols.length?sols.map((s,i)=>`<div class="solution"><strong>${esc(s.name)}</strong><p>${esc(s.text)}</p><div class="solution-actions"><button class="vote-btn" data-vote="${i}">👍 ${s.votes}</button>${s.accepted?"<span class='status solved'>Accepted</span>":""}</div></div>`).join(""):'<p class="muted">No solutions yet. Be the first to help.</p>'}</div></section><aside class="detail-card"><h3>Share a solution</h3><form id="solutionForm"><label>Your name<input class="input" name="name" required value="${esc(currentUser()?.name||"")}"></label><label>Your solution<textarea class="input" name="text" rows="6" required placeholder="Explain a practical solution..."></textarea></label><button class="btn btn-primary" type="submit">Post Solution</button></form></aside></div>`;
document.getElementById("solutionForm").addEventListener("submit",e=>{e.preventDefault();const d=new FormData(e.target);sols.push({name:d.get("name"),text:d.get("text"),votes:0,accepted:false});localStorage.setItem("ps_solutions_"+id,JSON.stringify(sols));p.solutions=sols.length;const all=getProblems();const idx=all.findIndex(x=>x.id===id);if(idx>-1)all[idx]=p;saveProblems(all);render()});
document.querySelectorAll("[data-vote]").forEach(b=>b.addEventListener("click",()=>{sols[+b.dataset.vote].votes++;localStorage.setItem("ps_solutions_"+id,JSON.stringify(sols));render()}))}
render();
});
